#!/bin/bash
export PROJECT_NAME=SpringWebMVC
export WORKING_DIR=$(pwd)
export SERVER_DIR=/opt/glassfish/glassfish

cd $WORKING_DIR
gradle clean assemble

echo "Deploy war file to server"
resultWar=${WORKING_DIR}/build/libs/${PROJECT_NAME}.war
if [ -s $resultWar ]
then
    cd ${SERVER_DIR}/bin
    ./asadmin undeploy $PROJECT_NAME
    ./asadmin deploy $resultWar
else
    echo "Build failed thus don't deploy to server"
fi
